pipeline{
    agent any
    stages{
        stage("build"){
            steps{
                sh 'echo "this is buld step"'
            }
        }
        stage("test"){
            steps{
                sh 'echo "this is testing step"'
            }
        }
        stage("deploy"){
            steps{
                sh  'echo "this is the deploy step"'
            }
        }
    }
}
